# Generated by Django 6.1.1 on 2026-10-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher / Faculty'), ('developer', 'Developer'), ('other', 'Other')], default='student', max_length=20)),
                ('institute', models.CharField(blank=True, max_length=150)),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Overall experience')),
                ('theory_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Theory clarity')),
                ('simulation_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Simulation usefulness')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('just_right', 'Just right'), ('hard', 'Hard')], default='just_right', max_length=20, verbose_name='Difficulty level')),
                ('liked', models.TextField(blank=True, verbose_name='What did you like?')),
                ('improvements', models.TextField(blank=True, verbose_name='What should we improve?')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='I would recommend this lab to others')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
