# Generated by Django 6.1.1 on 2026-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='quiz_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Pretest/Posttest quality'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sections_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(default='django', max_length=20),
        ),
    ]
