# Generated by Django 5.2.17 on 2026-10-03 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    """Give existing posts a unique slug before the unique constraint is added."""
    Post = apps.get_model('blog', 'Post')
    taken = set()
    for post in Post.objects.order_by('pk'):
        base = slugify(post.title)[:190] or 'post'
        slug, n = base, 2
        while slug in taken:
            slug, n = f'{base}-{n}', n + 1
        taken.add(slug)
        post.slug = slug
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_feedback_quiz_rating_feedback_sections_used_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # 1. add slug without the unique constraint, 2. fill it, 3. make it unique
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, default=""),
            preserve_default=False,
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name; filled from the title if left empty.",
                max_length=200,
                unique=True,
            ),
        ),
    ]
